"use client"
// import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { ApolloProvider } from "@apollo/client";
import createApolloClient from "./../lib/apolloClient";
import { UserProvider } from '@auth0/nextjs-auth0/client';
const poppins = Poppins({
  weight: ["300"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
const apolloClient = createApolloClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>

        <ApolloProvider client={apolloClient}>
      <body className={`${poppins.variable} font-sans`}>
        {children}
      </body>
        </ApolloProvider>
      </UserProvider>
    </html>
  );
}
